development:
  adapter: postgresql
  pool: 5
  encoding: unicode
  database: pirozhki_development
  username: dbuser
  password:

test:
  adapter: postgresql
  pool: 5
  encoding: unicode
  database: pirozhki_test
  username: dbuser
  password:

production:
  adapter: postgresql
  pool: 5
  encoding: unicode
  database: pirozhki_production
  username: pirozhki
  password: REPLACE_ME
