test:
  instagram:
    proxy:
    request_delay: 0
    client_id: REPLACE_ME
    client_secret: REPLACE_ME
  export:
    type: stdout
  newrelic:
    enabled: false
  rollbar:
    enabled: false
  logging:
    type: stdout
